In [1]:
import pandas as pd
import numpy as np

# 넘파이(numpy)

- ndim: 축의 개수
- shape: 배열의 차원정보
- size: 배열 안에 있는 원소의 총 개수
- dtype: 배열 원소의 자료형



In [6]:
narry = np.array(range(5))
print(narry, type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5


In [10]:
narr4 = np.zeros((2,2), dtype='int64')
narr5 = np.ones((2,2))
narr6 = np.full((3,3),3)
narr7 = np.full((3,3), 'number')
narr8 = np.eye(3)
print(narr4, narr4.ndim, narr4.dtype, narr4.shape, narr4.size, type(narr4))
print(narr5, narr5.ndim, narr5.dtype, narr5.shape, narr5.size, type(narr5))
print(narr6, narr6.ndim, narr6.dtype, narr6.shape, narr6.size, type(narr6))
print(narr7, narr7.ndim, narr7.dtype, narr7.shape, narr7.size, type(narr7))
print(narr8, narr8.ndim, narr8.dtype, narr8.shape, narr8.size, type(narr8))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>


## 2차원 배열

In [14]:
print(list(range(10)))
print(np.arange(2,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


In [12]:
arr1 = np.array([[0,0],[0,0]])
print(arr1, arr1.dtype, arr1.ndim, arr1.shape, arr1.size, type(arr1))

[[0 0]
 [0 0]] int64 2 (2, 2) 4 <class 'numpy.ndarray'>


In [15]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
print(arr2, arr2.dtype, arr2.ndim, arr2.shape, arr2.size, type(arr2))
print(arr3, arr3.dtype, arr3.ndim, arr3.shape, arr3.size, type(arr3))

[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 2 (3, 3) 9 <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 2 (3, 3) 9 <class 'numpy.ndarray'>


In [35]:
#1
a = np.arange(1,22).reshape(3,7)
print(a)
print('---------------------------')
#2
b = np.array([1,2,3,4,5,6,7]).reshape(7,1)
print(b)
print('---------------------------')
#3
c = np.arange(1,11).reshape(5,2)
print(c)
print('---------------------------')
#4
d = np.arange(1,22).reshape(3,7)
print(d)
print('---------------------------')
#5
e = np.arange(1,13).reshape(4,3,1)
print(e)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
---------------------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
---------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
---------------------------
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
---------------------------
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [39]:
print(d[0][3:])
print(d[1][3:])
print(d[2][3:])

[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [42]:
#  d[3:8, 3:8, 3:8]

In [44]:
#브로드캐스팅
np1 = np.array([6,7,8,9,10])
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [45]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
print(br1*br2)

[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]
